package org.byteworks.lexer;

public enum TokenType {
    UNKNOWN, PLUS, PLUSPLUS, MINUS, MINUSMINUS, MULTIPLY, DIVIDE, LPAREN, RPAREN, EOF, EOL, NUMBER, IDENTIFIER,
    ASSIGNMENT, FUNCTION_DEFINITION, COMMA, ARROW, LBRACE, RBRACE, COLON
}
